sudo: false
language: node_js
node_js:
- '4.1'
services:
- docker
env:
  global:
  - secure: vKbhkYa/ZQFCgkqmkZ99m4B/Rb6qZ0ci22Da0G3pt48IjZUgDEOuhTw5NBk4WDd2hvhI9oJSlOfEfEdIrOFSQaBcSrDufMbdKAlRkwnnObOlhejO3ZGXiqvPUf/crz/5/FVEUJkzlUwojzc/kC2zWdLFAzcBey91EW7Dc2UAY+0jHTjPqM7Xz/nHds2Vp2aE5AXB57YfQ7Cuc/wGy47C9t7Bn23NHPuUF6nrycDwDQxSMjZ7rIpVO2/IH0qOi2gfkiEOtyC3s45IxwXagOyK+JCGIpv4YIbjG7xooA9Cg4bdkONlZvugf3qVZVWw1swYESnTsWU2jRV0r/G9VL2QIirp+erWmn0khFdoajJdcLFzRl0KNNs7FN2/mOIG74uqra8lNN01g3s3+xxdxyW8F7lpjmswz8CfLs70/BmVh2aXM1+eWnB94BWpSN1D5qhbN7o5do4djekc6sxPC52v5DcboxgVADDIK3rr12nn8gwvK+b2Jysd28vy3xs/QEDvgpGIbKwbtXRFhwLVFGgrT9akDHsmjzZNd3V5tlA1oZxkuyxkxjUReOtwettX2JgAtIZqVVb1AD8FifST0/HwLOpyJDJZNz5mv4TuNVbSPfWbzo1MBKHoFpmeHRSsmuKwJTptf7jTcasCArcoo4V3Q01HYd4ctZ992nRMGCZxysk= // IRON_TOKEN
  - secure: SmcAy/WUpq8y1h6gHFTnCS3W2IUF0pwGXgp1EiMPHA82Ip3/WTwtQLELdo+g1WUdMsTYE6O9O0YVJ3vfiszvKoRZVJKMj32SiROOJsjX656j7ABAgol5sXOcdsNbdmWXd+riXBdvfZdEP6qj6zcOh344dzn7D0Mb2nsXD7lFjL0T4j+7IK+NOuJky2eumvxzvn2oIpWoTqsDg606NZj2Tq5sGIyW86LrqH9tu0eaIFQ8l9AK6rK8wbrM37BhzDvPbawfZQIE2FEHkFFuaxblY9Z+EE8j48Eqee9Xk8BAsaJw2py1ZtpJZQNR8wDTZ8GAL3IDfHIGMGhZggc2liAjbJg6wsYXHhixLi7SfEOBGXMKboU7upH2xTOXEACELBxOb4+aCYlKtu2sZkDqpZr0Aw2vysWJQbgESJZrTtvpQDtn6fmlO/IaxV1uU1LbHgMc97WYR6/a7bPpgugtYTgRtovDsH8qZiEqhjWwsKXuHauQxcn4voemvWo/2lhys3bn77wfFGqTYKBBGZdY0l/oSpVaad9/rx0UANpJCnIpq7loFl94pCXk4l4JSWp3/sYe4/MHy8EgWxwMvP89/3YTQQIv5DI/5FxEicaWRKyLqfoTYxULIXk8cuhFyKTbe0ealWpAdIHon9ntZr8reL8yhtJsfEp+b53gKF34BBFMsYY= // IRON_PROJECT_ID
install: echo nothing to install
script: docker-compose run --rm test
deploy:
  provider: script
  script: ".build_scripts/deploy.sh"
  on: master
